### ISSUE TITLE
Implement vis_parameters: map type

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#103]
Datasets and collections have various locations maps of their features appear. For the home page and gallery, it **_may_** be desirable to display features as a heat map tileset, or as an 'ordinary' tileset, regardless of feature type (Point, Polygon). If a dataset or collection has a tileset (due to meeting a size threshold) presumably its default display in home or gallery can be that tileset, albeit in a small window. But for large point datasets/collections, a heatmap tileset may be desirable. In this case, it **_could be_** a user choice. And if it were, the option would conditionally appear on the user's "builder" page, along with other vis_parameters. Note that sequence is only an option for Place Collections.

- All
  - home page if featured != null
  - "gallery" if public == True
- Dataset
  - owners' browse page (ds_browse.html)
  - published page (ds_places.html). Always visible to owner; public if public == True
- Place collection
  - publication page (place_collection_browse.html). Always visible to owner; public if public == True
- Dataset collection
  - publication page (ds_collection_browse.html). Always visible to owner; public if public=True

**Comment by docuracy** [comment]
KG: I think there is only one place a question could be put to the user about map type: whether a big point dataset or collection gets a heatmap for display on the home page if/when featured and on the gallery page if/when made public.
