### ISSUE TITLE
Map Page Test URLs

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#105]
- [x] Portal http://localhost:8001/places/portal/
- [x] Search http://localhost:8001/search/
- [x] Places http://localhost:8001/datasets/12/places
- [x] Map & Table http://localhost:8001/collections/11/browse_pl
- [x] Home http://localhost:8001/
- [x] Gallery http://localhost:8001/datasets/gallery/datasets/
- [x] Dataset Browse http://localhost:8001/datasets/12/browse
- [x] Areas http://localhost:8001/areas/create/
- [x] Tasks http://localhost:8001/datasets/7/addtask <-- Accessed through "My Data", then pick a "reconciling" dataset
- [x] Review http://localhost:8001/datasets/9/review/... <-- Accessed through "My Data", then pick a "reconciling" dataset

**Comment by kgeographer** [comment]
all boxes checked, closing
