### ISSUE TITLE
bug: payload for place collections with null geometries

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#131]
If a place collection includes place records for which there is no geometry, (e.g. Ibn Batutta), then place_collection_browse.html hung. Added logic to create null geometries in `fetch_mapdata_coll()` and page now displays, but only records with geometry appear in data table.

**Comment by kgeographer** [comment]
http://localhost:8001/collections/1/browse_pl

The Ibn Batutta collection has ten places, and for me, only 4 turn up in its table - the 4 that have geometry

<img width="1364" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/c9aaa31c-8f9c-4ea1-aa9a-3a842efda2c6">
<img width="417" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/87642830-2e96-4965-b2f6-21c24022ca73">

**Comment by docuracy** [comment]
I think that might be an _absent_ geometry problem, rather than a `null` geometry one. Will investigate further.

**Comment by docuracy** [comment]
Problem was this line:

`if len(t.place.geoms.all()) > 0:`

No features were being created under that condition.
