### ISSUE TITLE
Ecoregions tiles, offer on portal

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#136]
The ecoregions data is large, and not worth making a dataset just to get it in the tileset-making pipeline, so...

- [x] create a tileset for it directly on tileboss, and
- [ ] make the layer available on the Place Portal page

Data here: https://drive.google.com/drive/folders/1A8EZAS7ACD_NluwhfzPoM5sPq0HRZa_k?usp=drive_link
- a shapefile zip; more attributes than we need;
- `eco_name` is an identifier back to wiki landing pages, e.g. https://en.wikipedia.org/wiki/Northern_Mesoamerican_Pacific_Coast_Mangroves
-

**Comment by docuracy** [comment]
- [ ] Create ecoregion label point locators in QGIS and add to geopackage
- [ ] Regenerate multilayer `ecoregions.mbtiles`:
    - [ ] Polygons
    - [ ] Labels
- [ ] Add ecoregion source and layers to whg-basic styles' json:
    - [ ] variable fill-color based on `color` property
    - [ ] Use `whg:switchgroup` and `whg:switchlabel` metadata properties to ensure addition to style switcher
