### ISSUE TITLE
Temporal control

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#14]
Non-integer values are sometimes displayed in the tooltip, and not reflecting precisely the values in the boxes at either end of the scale. Probably related to the imprecise positioning of the slider buttons, which tend to jump on activation and deselection.

**Comment by docuracy** [comment]
`buffer` needed to be rounded in `mapControls.js`:

```
		const buffer = Math.ceil(range * 0.1); // 10% buffer

		// Update the temporal settings
		mapParameters.controls.temporal.fromValue = ds_list_stats.min;
		mapParameters.controls.temporal.toValue = ds_list_stats.max;
		mapParameters.controls.temporal.minValue = ds_list_stats.min - buffer;
		mapParameters.controls.temporal.maxValue = ds_list_stats.max + buffer;
```

**Comment by docuracy** [comment]
Sliders by default will jump if not clicked in their centre-points - see https://stackoverflow.com/questions/58912344/make-input-range-not-jump-when-i-hit-thumb-not-exactly-in-center

**Comment by docuracy** [comment]
Fixed with customised slider handler function `alignSlider`.

**Comment by kgeographer** [comment]
The .tick style conflicts with a built-in .tick used by D3 in the place portal histogram. Don't want to patch the library, so maybe easiest to rename the style in dateline.css?

**Comment by docuracy** [comment]
Rather than renaming, it would be a good idea in any case to limit the scope of the dateline css by including additional parent identifiers - so prefix everything with a #dateline identifier perhaps?

**Comment by kgeographer** [comment]
Sure, whatever works! place_portal looks for a .tick style and needs D3's
