### ISSUE TITLE
Tileset Creation Integration

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#155]
**unit test(s)** to confirm automated tileset generation working (welcome to django unittests!; [listing tests here](https://github.com/WorldHistoricalGazetteer/whg3/blob/staging/tests.md); cf. `/tests/test_*`). The bot is good at tests.

KG: Glancing at previous tileset-related test work I did, the request for tileset generation comes from `datasets.signals.handle_public_flag`, which initiates `request_tileset()` if `complexity` > a threshold. The signal on the Collection model does not (yet) use the complexity function. Guess I got distracted. But I did not realize that maybe the tileset should(?) be generated on create of a big one (dataset, collection).

When you create a dataset, a map for it is immediately visible in `ds_browse.html`, the owner’s private space. They can also preview it in `ds_places` (the pub page), which others won’t see until it is public. So it’s an open question as to whether. the map in `ds_browse` should display a tileset for huge datasets. Dataset and Place Collections have no similar ‘owner preview’ page. All that suggest changes to `ds_browse.html` (? dunno).

I guess the thing that needs a (re)think is whether all datasets and collections get a tileset automatically if they are huge (> 10k points? n vertices). So any further tileset testing has to be preceded by ensuring the code is currently doing what we want, which is preceded by deciding what we want!

On save of dataset w/ 'geom complexity' > a threshold:
- tileset request is made
- new tileset exists
- tileset accessible
- threshold can be arbitrarily 
- same for collections except
  - signal not currently looking at complexity
  - for DCs, it's on dataset add
  - for PCs, ??

**Comment by docuracy** [comment]
Required steps:

- [ ] Extend `tileboss/tiler/tiler.js` to provide a `delete` function for use in testing, initially
- [ ] Add complexity test for Collections
- [ ] Add size test for both Collections and Datasets
- [ ] Handle any (short) delay in tileset creation in `ds_browse.html`

**Comment by kgeographer** [comment]
This seems to be complete - if so, let's close it
