### ISSUE TITLE
`base.html` => `base_webpack.html`

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#158]
### Switch contact links to `<a data-whg-modal="/contact_modal/">`

- [x] ./accounts/templates/register/confirmation_sent.html
- [x] ./collection/templates/collection/ds_collection_browse.html
- [x] ./collection/templates/collection/ds_collection_build.html
- [x] ./collection/templates/collection/place_collection_browse.html
- [x] ./collection/templates/collection/place_collection_build.html
- [x] ./datasets/templates/datasets/dataset_create.html
- [x] ./datasets/templates/datasets/dataset_create_empty.html
- [x] ./datasets/templates/datasets/dataset_delete.html
- [x] ./datasets/templates/datasets/ds_addtask.html
- [x] ./datasets/templates/datasets/ds_metadata.html
- [x] ./datasets/templates/datasets/ds_reconcile.html
- [x] ./datasets/templates/datasets/ds_status.html
- [x] ./datasets/templates/datasets/review.html
- [x] ./datasets/templates/datasets/volunteering.html
- [x] ./main/templates/main/about.html
- [x] ./main/templates/main/contact.html
- [x] ./main/templates/main/documentation.html
- [x] ./main/templates/main/licensing.html
- [x] ./main/templates/main/v3_new.html
- [x] ./main/templates/main/workbench_3col.html
- [x] ./main/templates/tutorials/site_guide.html
- [x] ./main/templates/tutorials/walkthrough.html
- [x] ./resources/templates/resources/resource_create_bogus.html

### Rationale

`base_webpack.html`:
- loads webpack/base.bundle.js
- loads webpack/base.bundle.css
- loads any blocks included in a template for:
    - `maplibre`
    - `extra_head`
    - `deferredScripts` 
    - `inlineScripts`

The `base.bundle.js` includes CDN fallbacks, and initialises/disambiguates Bootstrap tooltips, the WHG Modal, Spinner, and turf scripts if maplibre is in use.

### Possibly Obsolete?

checked means deleted or commented out; strikethrough means not obsolete

- [x] ./areas/templates/areas/area_create_og.html
- [x] ./collection/templates/collection/ds_collection_summary.html
- [x] ./collection/templates/collection/place_collection_summary.html
- [x] ./collection/templates/collection/collection_gallery.html
- [x] ./collection/templates/collection/ds_collection_browse_foo.html
- [x] ./datasets/templates/datasets/ds_nav.html
- [x] ./datasets/templates/datasets/libre.html
- [x] ./resources/templates/resources/teaching_og.html
- [x] ./search/templates/search/home.html
- [x] ./search/templates/search/advanced.html

### Map upgrade required Leaflet -> MapLibre

- [x] ./resources/templates/resources/teaching.html

### Template pages currently using `main/base.html`: 

(issue) = problem; (a) = archived/deleted; (def) = deferred

- [x] (issue #293 ) ./main/templates/main/dashboard_admin.html
- [x]  ./datasets/templates/datasets/volunteering.html
- [x] ./accounts/templates/register/invalid_token.html
- [x] ./accounts/templates/register/confirmation_success.html
- [x] ./accounts/templates/register/password_reset_confirm.html
- [x] ./accounts/templates/register/confirmation_sent.html
- [x] ./areas/templates/areas/area_delete.html
- [x] ./collection/templates/collection/collection_group_gallery.html
- [x] ./collection/templates/collection/collection_group_detail.html
- [x] ./collection/templates/collection/collection_group_create.html
- [x] ./collection/templates/collection/collection_group_delete.html
- [x] ./main/templates/main/downloads.html
- [x] ./main/templates/main/dashboard_user.html
- [x] ./main/templates/main/usingapi.html
- [x] ./main/templates/main/licensing.html
- [x] ./main/templates/main/publications.html
- [x] ./main/templates/main/credits.html
- [x] ./main/templates/main/dashboard.html
- [x] ./main/templates/main/v3_new.html
- [x] ./main/templates/main/documentation.html
- [x] ./main/templates/main/contributing.html
- [x] ./main/templates/announcements/announcement_confirm_delete.html
- [x] ./main/templates/announcements/announcement_list.html
- [x] ./main/templates/announcements/announcement_form.html
- [x] ./collection/templates/collection/collection_delete.html
- [x] ./datasets/templates/datasets/dataset_create.html
- [x] ./datasets/templates/datasets/dataset_delete.html
- [x] ./datasets/templates/datasets/ds_reconcile.html
- [x] (def) ./main/templates/teaching/asian_history.html
- [x] (def) ./resources/templates/resources/resource_detail.html
- [x] (def) ./resources/templates/resources/asian_history.html
- [x] (def) ./resources/templates/resources/resource_create.html
- [x] (def) ./datasets/templates/datasets/dataset_create_empty.html
- [x] (def) ./elastic/templates/elastic/place_relocate.html
- [x] (def) ./elastic/templates/elastic/index_admin.html
- [x] (def) ./whg/templates/whg/500.html
- [x] (def) ./main/templates/main/404.html
- [x] (def) ./main/templates/main/500.html
- [x] (def) ./whg/templates/whg/404.html
- [x] (def) ./main/templates/home/builder.html
- [x] (a) ./places/templates/places/place_relocate.html
- [x] (a) ./main/templates/main/contact.html
- [x] (a) ./main/templates/main/api.html
- [x] (a) ./main/templates/main/modal.html
- [x] (a) ./main/templates/home/pipeline.html
- [x] (a) ./main/templates/home/build_new.html
- [x] (a) ./main/templates/main/system.html
- [x] (a) ./main/templates/main/base_template.html
- [x] (a) ./main/templates/main/tutorials.html
- [x] (a) ./main/templates/main/status.html
- [x] (a) ./main/templates/main/guides.html
- [x] (a) ./main/templates/main/community.html
- [x] (a) ./main/templates/tutorials/collections.html
- [x] (a) ./main/templates/tutorials/create_lptsv.html
- [x] (a) ./main/templates/tutorials/beta.html
- [x] (a) ./main/templates/tutorials/traces.html
- [x] (a) ./main/templates/tutorials/template.html
- [x] (a) ./main/templates/tutorials/place_collections.html
- [x] (a) ./main/templates/tutorials/walkthrough.html
- [x] (a) ./main/templates/tutorials/site_guide.html
- [x] (a) ./main/templates/tutorials/accordion.html
- [x] (a) ./main/templates/tutorials/choosing.html
- [x] (a) ./main/templates/tutorials/dataset_collections.html
- [x] (a) ./main/templates/tutorials/contributing.html
- [x] (a) ./datasets/templates/datasets/data_datasets.html
- [x] (a) ./datasets/templates/datasets/data_resources.html
- [x] (a) ./datasets/templates/datasets/public_list.html
- [x] (a) ./datasets/templates/datasets/data_collection_groups.html
- [x] (a) ./datasets/templates/datasets/data_areas.html
- [x] (a) ./datasets/templates/datasets/data_collections.html
- [x] (a) ./api/templates/api/union-dummy.html
- [x] (a) ./resources/templates/resources/resource_create_bogus.html

**Comment by kgeographer** [comment]
Deferring this for 1 June milestone

**Comment by docuracy** [comment]
To simplify the process, Base Webpack will now handle inline scripts, but there's a long list of templates (see above) to be worked through.

### Replace:

{% extends "main/base.html" %} -> {% extends "main/base_webpack.html" %}

### Move any remaining JavaScript:

Strip out of `<script>` tag and out of `$(document).ready` function and place inside:

```
{% block inlineScripts %}
{% endblock %}
```

### Remove any:

' style="min-height: calc(100vh - 210px);"' or similar in main `.container`

`{% load leaflet_tags %}`

```
{% block maplibre %}
{% endblock %}
```

**Comment by docuracy** [comment]
The following files have  within their inline scripts, which need to be either removed or replaced with JavaScript comments because they break `base_webpack`:

- [ ] /collection/templates/collection/collection_group_detail.html
- [ ] /collection/templates/collection/ds_collection_summary.html
- [ ] /collection/templates/collection/place_collection_summary.html
- [ ] /datasets/templates/datasets/data_collections.html
- [ ] /datasets/templates/datasets/dataset_create.html
- [ ] /datasets/templates/datasets/dataset_create_empty.html
- [ ] /datasets/templates/datasets/public_list.html
- [ ] /elastic/templates/elastic/place_relocate.html
- [ ] /main/templates/main/modal.html
- [ ] /main/templates/tutorials/site_guide.html
- [ ] /places/templates/places/place_modal.html
- [ ] /places/templates/places/place_relocate.html

**Comment by docuracy** [comment]
@kgeographer :

Is `/places/templates/places/place_modal.html` obsolete? It's still using `main/base_modal.html`.

Otherwise, _all_ pages now use `base_webpack.html`, and I wonder if the other bases might be deleted?

- [ ] `main/base_modal.html`
- [ ] `main/base.html`
- [ ] `main/base_template.html`
