### ISSUE TITLE
Bug/Snag Inventory

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#165]
Go over every click on every SG page; note below **the page in question** and anything needing attention or not working.

**General**
- All pages
    - [x] Replace tooltip white on black center-justified styling with something less jarring: e.g. black on white, left-justified
- Home: http://localhost:8001/
    - [x] Attribution button misplaced (too high)
    - [x] On initial load, features for 1st object (collection number 2 typically) don't display, but when it comes around in the circuit, they do
    - [x] ~Loading of one of the featured datasets is leaving a map spinner~ **NB some sample datasets are dicey for unknown reasons; set `featured - NULL` on a few, now all display w/above caveat**
    - [x] Remove footer text (development deferred to #200)
- Gallery: http://localhost:8001/datasets/gallery/datasets/
    - [x] Something off with the map padding for all datasets/collections
    - [x] ~Atlas of Mutual Heritage in gallery missing tileset error
    `jquery-3.6.3.min.js:2 
 GET http://tiles.whgazetteer.org:8080/data/datasets-40.json 404 (Not Found)`~ SG: I can't replicate this - perhaps it's gone away, or perhaps you have a dodgy version cached in LocalStorage?
- Search: http://localhost:8001/search/
    - [x] ~**kg**: Remove tooltip from input! **sg** I suggested (2 below) to keep it but hide on focus; **kg** removed, sorry!~
    - [x] Clear previous results when Advanced Options or Spatial Filter is changed
    - [x] On clear, display #initial_results blurb, not no_results message
    - [x] Clear search mode and input tooltips on focus (search mode tooltip is now disabled after focus so will appear again only on the next visit to the page; input tooltip additionally has a localStorage variable which will prevent its reappearance even on revisiting).
    - [x] Spatial filter text input: remove non-bs title, and clarify bs-tooltip wording wrt Region/Country dropdown
    - [x] ~Portal links require tooltips~ **kg: disagree**
    - [x] ~Results require tooltips to explain click action (remove cursor: pointer)~ **kg: disagree**
    - [x] Increase (even remove?) #result_container max-height **kg: not if it means scrolling the map out of view** **sg: nope - it's limited to the viewport height**...**show me :^)**
- Place Portal: http://localhost:8001/places/12346428/portal/
  - [x] `$(".pop-dataset").popover({` for dataset source got lost; added to portal.js but event propagates to #source_box action, unlike the notes button 
- Areas: http://localhost:8001/areas/create/
    - [x] Draw areas tab generates this error: `areas.bundle.js:165 Uncaught TypeError: Cannot read properties of undefined (reading 'clearSource')`
    - [x] Form should have placeholder texts instead of `title` properties
    - [x] Implement Select2 for country selection (as on Search and Gallery pages)
    - [x] Poor bs/flex layout wrt column margins
- Tooltip Initialisation:
    - [x] Remove from `base_webpack.js` dependencies. **@kgeographer: Tooltips are now all initialised by delegation from the `body` in `base.js`: all that is required for an element to have a tooltip is for it to have a `data-bs-toggle="tooltip"` attribute.**

**Datasets**
- Dataset Browse: http://localhost:8001/datasets/28/browse
    - [x] Detail div content in ds_browse.html does not display
    - [x] Tooltip/link on title & variants in detail not relevant here - all of this dataset
- Dataset publication: http://localhost:8001/datasets/28/places
    - [x] Tooltip/link on variants in detail not relevant here; for title only if indexed (has portal)
    - [x] Time slider should default to open
    - [x] Time control does not actually toggle date filtering (misleading tooltip)
    - [x] Time control `fa-question-circle` requires popover to replace "Lorem ipsum..."
    - [x] Image download and Exit fullscreen buttons lack BS tooltips
    - [x] Image download modal lacks title and should be Bootstrap
    - [x] Apart from the blue colour, the `pid` column lacks any indication that it links to another page (inconsistently, clicking anywhere else on the row highlights the feature), and in any case seems redundant now that links appear in the Detail box [@kgeographer: should the column perhaps be removed?] **yes, see below**
        - [x] some configurations of vis parameters cause 'add to collection' check boxes to disappear to the right; maybe just comment out the pid column [@kgeographer Not a complete solution, because the container has hidden overflow, so other columns become hidden when the screen width is not "wide". Fixed by allowing `overflow-x: auto` and setting the BS .row margin-right to auto (default behaviour causes persistent scrollbar). Also, have to set column to `visible: hide` rather than commenting it out because it has a data property that needs to be accessible.]
    - [x] Thumbnail image is limited to row height of title. Float it instead with a non-percentage max-height.
    - [x] Download and Metadata links have non-Bootstrap tooltips (i.e. titles): need to accommodate both tooltip and modal by using different tag for tooltips (i.e. not `data-bs-toggle`).
    - [x] Metadata `eyeball` icon not linked
    - [x] Metadata modal has a `permalink` tooltip with sometimes-missing content: tooltips in modals require specification of container, e.g. `data-bs-container="#metadataModal"`
    - [x] ~Citations _could_ usefully be offered in a selectable range of standard formats (see [https://citation.js.org/](https://citation.js.org/))~ **pls defer**

**Collections**
- [x] ~Redirection~(messy) 404 error should be set up to prevent browse_ds and browse_pl being used interchangeably on the wrong type of collection
- Place Collection Browse: http://localhost:8001/collections/11/browse_pl
    - [x] Sequence Player fails if no row has first been manually selected: e.g. http://localhost:8001/collections/11/browse_pl
- Dataset Collection Browse: http://localhost:8001/collections/2/browse_ds

**Comment by kgeographer** [comment]
Added an item under portal; some changes to portal js and css are in the latest staging (19:31 Turkey time 16 May), so work on this should follow an update to that staging

**Comment by kgeographer** [comment]
Since all the boxes are checked, closing this. Anything related or further on any of the items should surface in a new issue
