### ISSUE TITLE
Decommission livereload?

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#168]

**Comment by kgeographer** [comment]
livereload does result in speedy refreshes for me as I change things. please leave in place - at least for now - and in a few days I will see how I fare without it

**Comment by docuracy** [comment]
Solved with a separate `docker-compose-dev-minimal.yml` in which livereload is disabled together with selenium services, resulting in very significantly faster Docker network rebuild and page load times(for @docuracy at least).

**Comment by kgeographer** [comment]
more power to ya!
fwiw, docker-compose on the server doesn't load those things
