### ISSUE TITLE
Add place __set__ to place collection

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#173]
THE SITUATION (high priority for contract number 6)
The place portal page formerly had a radio button on the top line of each attestation 'card', and selecting one would make visible an 'add to collection' link, similar to what is still in place on the Dataset publication page, ds_places.html.

A new requirement is that instead of adding only one place record from the set displayed, a user can _only_ add the "entire" place - i.e. the set of all attestations displayed. The set corresponds of course to that identified by the `whg_id` from the index and the permalink for the portal page. This has several implications; best to start with what it means for the publication page (place_collection_browse.html) for the chosen place collection.

- the table has to list a single row for each __set__ 
- the map has to show a 'representative geometry' for the set
- the detail box _always_ shows only the annotation, so no change (?)
- there should be an indication that the listed place has multiple attestations (or only one if that's the case) and maybe there should be a link to its place portal page.

BUT...
- places are also added to a collection from Dataset publication pages (ds_places.html), so...
- the table and map will display both individual Place records from ds_places.html and some kind of summary record from place_portal pages.
- the payload to the page will need a uniform format for both kinds

ISSUES
- a Place instance membership in a place collection is now stored in the collections_collplace table AND in the trace_annotations table; the place is `place_id` in the former, `place` in the latter -- both are Place ids.
- the Place.id (pid) is no longer a singleton if coming from place_portal, but a set of pids
- so there are model changes to consider
- possibly there is just a new column added for both, `whg_id`, used in various places to get the component pids??

<img width="1060" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/647f685a-804b-4e26-9e0e-81e5684effe6">

**Comment by docuracy** [comment]
- [ ] Implement JQuery (or BS?) modal form on Portal page (e.g. http://localhost:8001/places/12346428/portal/)
- [ ] Back-end: is there an API to deal with the form submission and confirmation?
- [ ] Refactor `/mapdata` View for Place Collection along that already implemented for Dataset Collection
- [ ] See if everything works without any further tweaking (LOL, but it might)
- [ ] Add Portal or Place Detail links to table

**Comment by docuracy** [comment]
- [ ] Add `matches` @property to Place model (using `close_matches` table) which includes primary match as the first returned `pid`, based perhaps on number of `link` authority records and/or inclusion of the mediod.
- [ ] Add `primary attestation` flag to list on Place Portal
- [ ] Include **optional** inputs on Add to Collection form:
    - [ ] Dropdown (with disambiguation including perhaps popups) for altering chosen attestation
    - [ ] Checkbox for excluding other attestations
- [ ] Update Place Collection Browse to include:
    - [ ] `pid`-family feature geometries
    - [ ] links to distinct Places in the Attestation Detail box

**Comment by kgeographer** [comment]
Attestation detail should not reference all the distinct Places. As it stands, it simply has the attestation content. The place being annotated is in the table, so the connection is direct and obvious. The table row _could_ have a link to the place portal for those rows that came from one, or a link to a place detail page if it was added from a dataset. OR...that link could appear as 'place record' next to the title in the detail box. But not a list of the pids involved I think.
Not sure how you would indicate which is the 'chosen primary' when the modal loads...I guess the modal needn't be a little bitty thing
Apart from those, +1

**Comment by docuracy** [comment]
But then there would never be any indication of the curator's choice to include a pid family in the Collection.

I think the attestation detail _must_ indicate the distinct Places, because in this context what is being annotated is a chosen primary Place _and_ its family, not only the primary Place.

What is listed in the table for such annotations should be an aggregation of Places, not the Primary Place: the title and sequence from the annotation, but the start and end from the annotated pid's family.

The dropdown box would default to the primary pid - no need to indicate the chosen primary attestation in any other way.

**Comment by kgeographer** [comment]
the link could be 'place' or 'place set' -- I'm concerned about the number of pids, and while it may make sense to the author of the collection, anyone else encountering 17 pids (or 2 or 3) could fairly wonder, 'what the heck?'
that said I'm fine with whatever you conjure there, this is beta <- my new motto
