### ISSUE TITLE
Review screen map basemap, zoom and scale

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#176]
The maps on review.html and accession.html pages need 3 key features assisting the review/match process present in v2 but missing so far in v3. 

- 'street' basemap w/ numerous local names for reference; the basemap in v2 was ideal for this, hopefully can be approximated.
- a scale to indicate distance, varies on zoom
- buffer on zoom extent for more context

<img width="353" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/896ea7ab-fd10-4d1d-b9fd-5de6ebc950b3">

**Comment by docuracy** [comment]
- [ ] Basemap: **is the one now implemented on the Portal Page adequate for this?** (at high zoom levels it draws all of the OSM streets but without labelling them, and includes all of the OSM place-names).
- [ ] Scale control: see https://maplibre.org/maplibre-gl-js/docs/API/classes/ScaleControl/ - add to `whg_maplibre.js`.
- [ ] Increase map feature padding (for added context)

**Comment by kgeographer** [comment]
I much prefer the v2 map for review, but what do you think? You are a user 😉

**Comment by docuracy** [comment]
Perhaps include a Basemap selector with additional options including satellite and "vanilla" OSM?
