### ISSUE TITLE
Datasets & Dataset Collections need time filter option

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#177]
For some datasets **(and dataset collections)**, all or most records are temporally scoped (have meaningful start or start/end), so the ds_status **and ds_collection_build** pages now have a switch option to display the time filter slider on **their** pub pages. A simple boolean: show time filter, yes or no. The entire vis_parameters control would be confusing in those cases. I imagine flipping the switch writes a vis_parameters value to that objects record (initially NULL) with an ajax call, and flipping it back NULLs it again. The vis_parameters object would just need the settings that enable a slider. Sequence is not a factor for these. Did not draft a function b/c it gets into vis_paramets, b/c that is @docuracy territory.

<img width="638" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/bcd5f72c-a490-46bb-8a43-104d7d0d725e">

**Comment by docuracy** [comment]
Partial Overlap/Duplication: https://github.com/WorldHistoricalGazetteer/whg3/issues/159#issue-2224657561

SG: Digging into the configuration of temporal controls, I've just realised that `tableFunctions.js` is configured such that only place collections will ever have columns for `start` or `end` properties (or indeed `seq`). Is that how it should be? Do we not need to show such properties for datasets and dataset collections?

KG: About time controls…this hasn’t been thought out fully ... all Place records have at least a start value, but in the great majority of datasets, all of its places have the same year as a publication date of a source — not meaningful in the same way as ‘existed at’ or ‘attested at’ dates, and certainly not like the start/end in the annotations of a place collection. this leads me to think that a configuration option of a dataset should be something like a ‘my dates matter’ toggle - which would lead to a time slider appearing. For a handful of datasets, the time filter widget would be very good if not essential. I don’t think a player option makes sense.
maybe this needs a few more example datasets to work with, which I can do next week.

- [ ] Temporal control options on builder pages (sequencer, player-start-date, player-end-date)
    - [ ] Datasets (no options at present: no change proposed, display should use default of slider for both start- and end-dates)
    - [ ] Dataset Collections (no options at present: no change proposed, display should use default of slider for both start- and end-dates)
    - [ ] Place Collections (all 3 options at present: no change proposed)
- [ ] Temporal control configuration/test
    - [ ] http://localhost:8001/datasets/10/places (_both_ showing)
    - [ ] http://localhost:8001/collections/14/browse_ds  (_both_ showing)
    - [ ] http://localhost:8001/collections/13/browse_pl (date slider only)
    - [ ] http://localhost:8001/collections/11/browse_pl (sequencer only)

**Comment by docuracy** [comment]
- [ ] Upgrade `ds_collection_build` and `ds_metadata.html` to use `base_webpack`
- [ ] Drop `VisualisationControl` into both
- [ ] Configure `VisualisationControl` in both

**Comment by kgeographer** [comment]
I very much do not want the full vis control in these two pages. Time? Y/N is all they need.

**Comment by kgeographer** [comment]
I see I put the Display temporal filter" switch in both ds_status and ds_metadata. I intended to remove it from ds_metadata, and have that choice be in ds_status alone, with that space in ds_metadata used for the file information instead.

I do not believe the entire VisualisationControl is necessary, for either ds_collection_build or ds_status, only a switch. If the data has meaningful dates, the switch writes a `vis_parameters` value that cause a time filter and start/end columns to appear.

**Comment by docuracy** [comment]
KG: "...if someone chooses to display a time slider for a dataset or dataset collection, because their dates are meaningful (i.e. related to the place's existence, not the pub date of the source), then start and end columns should be available. So the toggle switch label should reflect that, and 'show slider' should in fact enable start/end columns, not only a slider".

**Comment by kgeographer** [comment]
My take is that there is one configuration of a vis_parameters object that applies 'show slider' and 'show start/end'. Therefore it is a binary. If there is meaningful time, then add a a vis_parameters object to the record. If there isn't, don't. So the use choice is y/n and the interface needs to reflect that. 
I am assuming that when a dataset or dataset collection pub page loads, it looks for the value in vis_parameters, if there is one. In that case, there is a single configuration of that field that applies, and the user should not be presented with the full complexity.
It should not be a choice to say time slider yes but start/end no. Too many choices.
