### ISSUE TITLE
Fix use of `CloseMatches` in `PlacePortalView`

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#183]
Explanation in `places/views.py` file - currently fetching from Elastic index via `findPortalPIDs` instead of the `matches` Place `@property`.

**Comment by kgeographer** [comment]
Revisit after most/all data is in dev server database

"Explanation in places/views.py file":

    TODO:
    The following code is inefficient because the Place `matches` @property returns Place objects
    already sorted. The test data in the database is currently inadequate to allow refactoring of the code to make
    use of this, and so the Places are unnecessarily fetched and ordered a second time.
    
    pid-based portal_data currently uses Elastic index in order to get useful results: this should be replaced
    with the commented-out code-block to use the Place `matches` @property

**Comment by docuracy** [comment]
Fixed in PR #123. Final tidying up of redundant code required.
