### ISSUE TITLE
Script to build tilesets for production

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#189]
When data has been migrated from v2, large datasets and collections will need tilesets. In anticipation of that we need scripts (maybe make them a "django commands"?) that will run once, to 

- loop over a) datasets, b) collections
- if complexity > threshold, build a tileset

This can be coded and run as a test before the actual migration is complete

**Comment by docuracy** [comment]
- [ ] Add as Tileset module to Admin Dashboard|Tools
- [ ] Inventory of un-tiled "complex" datasets & collections, with buttons to Queue All or individually 
- [ ] Inventory of orphan tilesets, with buttons to Delete All or individually
