### ISSUE TITLE
Detail div in ds_browse not displaying

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#192]
As of last PR (188?) the detail div content in ds_browse.html does not display, with this error:

![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/9c826942-1c29-45e6-8119-ee036cc74466)

**Comment by docuracy** [comment]
OK - moving this to Bug/Snag Inventory
[#165](https://github.com/WorldHistoricalGazetteer/whg3/issues/165) to avoid Issue proliferation
