### ISSUE TITLE
Toggle GeoNames reconciliation hits in review.html

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#196]
Reconciliation now runs against a `wdgn` index that includes the previous 3.6m wikidata records and ~10m geonames records. The list of hits on the right for a given place record on the left will include all hits from both sources, but will filter the display:

- if there is >=1 hit with `dataset=="wikidata"` and >=1 with `dataset=="geonames"`, the Wikidata hits will display, the geonames ones will be hidden, and a button to "Show GeoNames records" appears near the top.
- if there are no Wikidata hits, and >=1 GeoNames hits, those will display
- if there are no GeoNames hits, then only the Wikidata hits display

This is a "beta" approach to providing more candidate matches for geocoding

The issue(s) are:
- the "Show GeoNames records" button toggles only the hit list, not the markers
- although Wikidata and Geonames are differentiated in the list with color, the markers are not

[A screen where this can be tested ](http://localhost:8001/datasets/30/review/e3170100-3af9-4188-9257-6060a38094cb/2?page=5)

**Comment by docuracy** [comment]
- [ ] Fix `"{% url 'datasets:review' pk=ds_id tid=task_id passnum=passnum %}"` in `review-common.js`

- `features.properties.ds` is either "wikidata" or "geonames", and features currently have a `green` property to indicate the data point being matched.

**Comment by kgeographer** [comment]
I think we should maintain the color scheme of v2, and v3 so far:
- the user record: green
- the hit record: orange if wikidata; blue-ish if geonames

The colors I used in the template on the id field should be changed to indicate that
- `text-bg-warning`, `text-bg-warning`
Also...the hover behavior on wikidata record globe icon works, but not on geonames records.

re: fwiw, `src_id`s - these are not unique; lots of datasets have 1, 2, 3, ...

**Comment by docuracy** [comment]
By `src_id` in this context I was referring to a "_" concatenation of a source identifier ("wd" or "gn") numerical id.

**Comment by docuracy** [comment]
@kgeographer: `datasets.views.review` has this line of code:
```
  authname = "Wikidata" if auth == "wd" else "WHG"
```
... which I think probably needs to be generalised to allow for GeoNames (it gets written into the `jsonb.citation` of PlaceGeoms). Similarly, there's a `write_wd_pass0` function and I wonder if that also needs to allow for GeoNames?

**Comment by kgeographer** [comment]
Sounds right. Off shopping, offline for an hourOn May 17, 2024, at 10:22, Stephen Gadd ***@***.***> wrote:﻿
@kgeographer: datasets.views.review has this line of code:
  authname = "Wikidata" if auth == "wd" else "WHG"

... which I think probably needs to be generalised to allow for GeoNames (it gets written into the jsonb.citation of PlaceGeoms). Similarly, there's a write_wd_pass0 function and I wonder if that also needs to allow for GeoNames?

**Comment by kgeographer** [comment]
re: _"Similarly, there's a write_wd_pass0 function and I wonder if that also needs to allow for GeoNames?"_

this is now working properly so I think this issue can be closed?

**Comment by docuracy** [comment]
I didn't actually address these:

- [ ] `authname = "Wikidata" if auth == "wd" else "WHG"` in datasets.views.review
- [ ] write_wd_pass0 function needs to allow for GeoNames

**Comment by kgeographer** [comment]
I did - done
