### ISSUE TITLE
Accession Page

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#202]
- [x] Accommodate changes in `review.js` and `review-common.js` (probably _some_ similar changes to those in `review.html`.
- [x] Colour all markers orange and remove numbering
- [x] Dataset Profile popovers are broken, and tooltips only appear on click
- [x] Concordance links are broken
- [x] Add Note button is broken
- [x] Place link is to API JSON - @kgeographer: is it OK that I've changed this to place detail?
- [x] Dataset link at top should go back to the ds_status page {% url 'datasets:ds_status' {id} %} and tooltip “Dataset status page”
- [x] The `already` alert should apply to both review and accession

**Comment by kgeographer** [comment]
What is remaining here? Close it?
