### ISSUE TITLE
dataset collections and close_matches

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#218]
The last truly breaking page load is for ds_collection_browse.html, the publication page. Loading any of them causes a timeout between nginx and gunicorn, as nginx waits 60 seconds then throws a 504 error. Output in the web container log varies.
Dataset Collections have undergone significant change between v2 and v3, as you know, and I’m not clear how the close_matches table is or isn't being used or whether that is a factor.

```
id title place count
2 Historical Gazetteer of the Middle East 6446
10 Historical Gazetteer of Central Asia 6704
130 alitest 2363
25 An Historical Gazetteer of Ukraine 3224
116 Historical Atlas of Poland in the 16th century 24626
129 foo 368
179 New African data 114864
123 Taiwan Communities, 1662-1894 974
172 Indigenous Place Names in North America 1126
127 Historical Gazetteer of Central Asia 2338
125 The Historical Middle East 4221
```
For the smallest, 'foo', the web container log reports this after the long wait, but the timeout 504 has already returned to the browser; the output varies by collection. for indigenous places 172, it did report some families:
```
DatasetCollectionBrowseView get_context_data() request.user whgadmin
join ['could', 'it', 'be'] , 
fetch_geojson_coll kwargs {'id': 129}
Collection 129: 368 places sorted into 0 families and 368 unmatched.
```

**Comment by kgeographer** [comment]
followup...it occurs that in v3 a dataset in a collection must have been indexed, and previously not. so for existing dataset collections, some datasets' places have no records in the 'whg' index. the upshot is that for collections containing unindexed datasets, there are no references to their pace ids in close_matches. For new dataset collections this would not be an issue.

**Comment by docuracy** [comment]
Several causes of delays have now been addressed with the refactoring and caching of `mapdata`. Removing my assignment to this Issue because (unless I'm mistaken) any remaining issues would relate to the transfer of data from v2 to v3 and therefore beyond my competence.
