### ISSUE TITLE
Pseudo-Portal for Unlinked Places?

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#223]
The place detail page is less pretty and considerably less informative about locations than the portal page. For unlinked places, why are we linking from search results to place detail rather than a single-source portal, @kgeographer ?

**Comment by kgeographer** [comment]
Legacy artifact. Search was always against the whg  index only. Now against whg + pub, so returning an “unindexed” record to a portal page is (more) feasible.
That said, there is a conceptual and ux issue…when viewing an unlinked (un-attempted-linked) record in a portal page, one can be easily confused. Notwithstanding that our users are clever(!). For an as-yet unlinked Istanbul record with one source card, one might wonder where the others are. This issue follows from a basic shortcoming (?) of the pipeline: you can publish without the last link/accession step

**Comment by docuracy** [comment]
@kgeographer: 

Is `/places/templates/places/place_modal.html` obsolete? It's still using `main/base_modal.html`.

Otherwise, _all_ pages now use `base_webpack.html`, and I wonder if the other bases might be deleted?

- [ ] `main/base_modal.html`
- [ ] `main/base.html`
- [ ] `main/base_template.html`

**Comment by docuracy** [comment]
### Search Page proposals

For example, search for "Glasgow"...

- [ ] Replace variant `view all` and `view fewer` links with the modular `More` / `Less` buttons already in use on the Portal page. Also standardise "Chronology" instead of "Timespans".
- [ ] Results should have a tooltip on hover, "Click to zoom on map".
- [ ] Unlinked results should have a dashed border.
- [ ] If there are only unlinked results, include a column-width button-like (but inert) banner stating `No Linked Results`.
- [ ] Unless there are no linked results, unlinked results should initially be hidden, headed with a column-width `Show/Hide Unlinked Results` button.
- [ ] Replace all `place portal` and `place detail` links with a `Place Details` button which leads in all cases to a Portal page. I don't think the word "portal" conveys anything meaningful to a new user.
