### ISSUE TITLE
Character Encoding in DB

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#229]
UTF-8 encoding needs to be enforced for toponyms (in fact on _all_ fields) on data submission, otherwise (for example in https://dev.whgazetteer.org/datasets/1120/places):

"title": "Terre Ad\u00c3\u00a9lie" (_Terre Adélie_) is rendered as "Terre AdÃ©lie"

Might it be necessary to convert the entire database, or are the Places in this Dataset (created October 2022) unusual?

**Comment by kgeographer** [comment]
Got lost in the radical refactor of validation. Assign to me

https://github.com/WorldHistoricalGazetteer/whg3/blob/60114e1b57656269d025cdd4265a2d8a9b50da10/datasets/views.py#L2481

**Comment by kgeographer** [comment]
I have re-inserted the test for utf-8 in the validation flow, so I'm closing this.
