### ISSUE TITLE
`place_type` table regularisation

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#238]
Regarding Search Page: "AAT place types can include both 'inhabited places' and 'inhabited place' - needs normalization on singular"

In fact 'inhabited place' is not an AAT place type: [aat:300008347](https://vocab.getty.edu/aat/300008347) is 'inhabited places'.

The `place_type` DB table includes jsonb in which:

- the labels are inconsistent with the identifiers, for example '{"label": "inhabited place", "identifier": "aat:300008375"}', where the label should be "towns" (and where the DB `aat_id` field is empty)
- the identifier is given as "aat:"

Rather than normalising DB query results, the DB entries themselves ought to be fixed. The Getty API might be of some use in a Management Command script.

**Comment by kgeographer** [comment]
At some point long ago, I decided I did not like the plural form - which are the actual terms in AAT. The types table reflects that, with separate term and term_full columns. Did not bother with some of the 'umbrella' terms in the hierarchy that are in fact never used.
I get that if it is a published vocabulary, then the vocabulary's term is 'official'. Guess I was playing fast and loose, with UX the driver over formal adherence. No longer have a view really but I guess if normalization is to take place it would involve pointing to the term_full column.

**Comment by docuracy** [comment]
Seems odd (to me, rather new to Django) that the `place_type` table in the WHG3 Dev DB doesn't have `term`, `term_full`, or `note` fields, but does have a `jsonb` field.

**Comment by kgeographer** [comment]
with `aat_fclass` (now) as
```
for type_obj in Type.objects.all():
    aat_fclass[type_obj.aat_id] = {
        "fclass": type_obj.fclass,
        "term_full": type_obj.term_full
    }
```

going from
`'label': aat_fclass.get(aat_type, {}).get('term') if aat_type else ''`
to
`'label': aat_fclass.get(aat_type, {}).get('term_full') if aat_type else ''`

also for existing:
```
UPDATE place_type
    SET jsonb = jsonb_set(jsonb, '{label}', '"inhabited places"', false)
    WHERE jsonb->>'label' = 'inhabited place';
```    
there may be a relative handful of others that used the singular 'term' but I don't want to worry about finding them now. up to @docuracy  whether to close this
