### ISSUE TITLE
Omit citation link for variants add from wikidata

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#245]
In `getPlace.js`, a block at ::51 (below) provides a tooltip for a variant if the PlaceName record has a label. We are now (at least in beta) allowing people to accept place name variants from Wikidata, so when a match is declared, >=1 PlaceGeom, PlaceLink and potentially PlaceName records are written to the db.

Because Wikidata does not source its variants, they should not have either a tooltip or a link. The `jsonb` field for a PlaceName looks like this for a newly added variant form WIkidata

`{"toponym": "Tala, Jalisco@sh", "citations": [{"id": "wd:Q3175338", "label": "Wikidata"}]}` -- the id should not be acted upon in this case.

```
if (id && (() => { try { new URL(id); return true; } catch { return false; } })() && label !== '') { // Check validity of id as a URL
		// If both id and label exist, wrap the name in a link with tooltip
		nameHtml = `<a href="${id}" target="_blank" data-bs-toggle="tooltip" title="${label}">${nameHtml} <i class="fas fa-external-link-alt linky"></i></a>`;
} else {
		// If only label exists, show tooltip without link
		nameHtml = `<span data-bs-toggle="tooltip" title="${label}" class="pointer">${nameHtml}</span>`;
}
```
I haven't pushed it out, but this is what it looks like with the current code. The non-links have a very nice tooltip, the links go nowhere :^(

<img width="466" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/e8ec7bef-10cf-45b4-8706-5fe6e2aad13a">

**Comment by docuracy** [comment]
I _think_ this is the correct behaviour based on (currently incorrect) data. A tooltip indicates the source of a variant, but a hyperlink is generated only if the id is a `http(s)://` URL.

Links are generated for everything in the received `links` array. _In this case the gn: id has additionally been assigned to wd:._

![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/42514781/21fb5536-c165-44cf-8890-b9c1101b6e5b)
![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/42514781/921a685f-0269-45e4-aaaf-2cf61bc53595)
![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/42514781/e849feea-4948-4801-b4b5-a46c0173dfee)
