### ISSUE TITLE
Place Collection Relation Colouring

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#246]
"In place collections, people can flag an annotation as being of a type/relation according to a vocabulary they make up with annotation keywords. The result is that places for each keyword are colored differently. We had this in place, and I remember coding a legend that appeared as a map overlay."

![image](https://github.com/WorldHistoricalGazetteer/whg3/assets/42514781/ae23135a-e8f2-40f3-b757-7d41adb5ea81)

**Comment by docuracy** [comment]
In `mapFunctions.js`, `colorTable` and `arrayColors` are imported from `utilities.js` but not used because this codeblock was removed:

```
	if (!!ds.relations && layer.id == 'gl_active_point') {
		let circleColors = arrayColors(ds.relations);
		colorTable(circleColors, '#mapControls');
		mappy.setPaintProperty(modifiedLayer.id, 'circle-color', [
			'match',
			['get', 'relation'],
			...circleColors,
			'#ccc',
		]);
		mappy.setPaintProperty(modifiedLayer.id, 'circle-stroke-color', [
			'match',
			['get', 'relation'],
			...circleColors,
			'#ccc',
		]);
	}
```

It needs to be refactored to work with `layerset.js`.

**Comment by docuracy** [comment]
I restored what was there before with regard to the map table and coloured markers, but now see that the annotation module (which you screenshot) does not use the `arrayColors` function and has only the two pre-determined `relation` options.

The `arrayColors` function is designed to return a set of perceptually-contrasting colours paired with a given set of relation strings, and so it would be useful to preserve it if at some point we intend to allow users to determine their own set of `relation` options. However, if you want to stick to the fixed options, @kgeographer, I can strip that out.

**Comment by docuracy** [comment]
... tracked down the following, loaded in `traces.views.get_form` (in `traces.templates.traceanno_form.html`):

@ property on Collection model:
```
  def kw_colors(self):
    colors = ['orange', 'red', 'green', 'blue', 'purple',
      'red', 'green', 'blue', 'purple']
    return dict(zip(self.rel_keywords, colors))
```

So the question, @kgeographer, is whether you want to use this fixed list of 5 repeating colours or a dynamic list of any number of distinct colours?

**Comment by kgeographer** [comment]
The idea is, and the code had been doing this...relation keywords are the user's own vocabulary - could be anything - stored in an array field. Each is assigned a color from an array of limited length - 5, 8 don't recall.

**Comment by kgeographer** [comment]
Went with 5 that seemed to render well in the existing basemap. A larger number would be great (there is no limit to the # of keywords allowed), as long as they appeared well and were distinguished from each other.On Jun 13, 2024, at 06:36, Stephen Gadd ***@***.***> wrote:﻿
... tracked down the following, loaded in traces.views.get_form (in traces.templates.traceanno_form.html):
@ property on Collection model:
  def kw_colors(self):
    colors = ['orange', 'red', 'green', 'blue', 'purple',
      'red', 'green', 'blue', 'purple']
    return dict(zip(self.rel_keywords, colors))

So the question, @kgeographer, is whether you want to use this fixed list of 5 repeating colours or a dynamic list of any number of distinct colours?

**Comment by docuracy** [comment]
OK, I've removed the predefined colours from `traces.views.get_form` and `traces.templates.traceanno_form.html`. Users no longer get any indication of which colours will be assigned to each relation label: this _could_ be done, but as the colours are dynamic depending on the number of distinct labels present at the time of rendering, it could be misleading.

![image](https://github.com/WorldHistoricalGazetteer/whg3/assets/42514781/e5f6a219-8f85-4685-87a5-6a72fa405193)
