### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#25]
`\main\templates\main\home_v30a.html`
http://localhost:8001/

### new functionality
- carousel of public datasets
   - bbox of extent
- carousel of public collections
   - bbox of extent
- map search box
  -   wired to ES
- advanced search options in expanded div
- content
  - text on left, below map

**Comment by kgeographer** [comment]
![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/a88f41b1-0895-4095-b62d-12e293fe69b4)

**Comment by kgeographer** [comment]
Search from home page fails, browser console:
```
An error occurred: TypeError: Cannot read properties of undefined (reading 'forEach')
    at renderResults (search.bundle.js:1891:10)
    at search.bundle.js:1768:13
Error {message: 'Input data is not a valid GeoJSON object.'}
```

**Comment by docuracy** [comment]
I can go ahead and recode this now that the Search page is stable. Saving the checkbox state is part of this.

**Comment by docuracy** [comment]
Fixed that.

**Comment by docuracy** [comment]
**TO DO**

- [ ] Find alternative to hull
