### ISSUE TITLE
Small Bug: Atlas of Mutual Heritage

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#255]
The link associated with dataset Atlas of Mutual Heritage is broken - https://dev.whgazetteer.org/datasets/819/places

Perhaps something I can fix once I have access to admin page

This is also a test for my first issue!

**Comment by kgeographer** [comment]
Tried the webpage link, to https://www.atlasofmutualheritage.nl/, came up for me. Is that the one you mean?

**Comment by alexstrb** [comment]
That's the one I mean. It won't open on my computer - tried Chrome and Microsoft Edge. And it also won't open on my colleagues computer either. Doesn't seem like an whg problem then.

**Comment by kgeographer** [comment]
> That's the one I mean. It won't open on my computer - tried Chrome and Microsoft Edge. And it also won't open on my colleagues computer either. Doesn't seem like an whg problem then.

I will keep poking at it

**Comment by kgeographer** [comment]
Fixed in production -- looks ok now
