### ISSUE TITLE
Cannot log into dev site

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#258]
Hello- I went through the process of trying to log into the dev site with my als512 email (this is the account I use for v2). I was able to put my email and pw in and then was sent an email from the system prompting me to follow an address and put in a new pw. When I clicked on that link (http://localhost:8001/accounts/reset/MTE5/c8tgfo-88f7a49717a0f68369cac8d4331f5a5a/) I got an error message that said "localhost refused to connect." Same thing happened yesterday. I waited until today to try again in case it was my computer being wonky. I tried the process from both Chrome & Edge. 

![Screenshot 2024-06-18 081256](https://github.com/WorldHistoricalGazetteer/whg3/assets/112724702/98c5e465-8175-42c3-94fd-607e7460d915)

**Comment by kgeographer** [comment]
my bad -- that localhost needs to change - on the list of last minute to do prior to launch - a little later in the day. sorry

**Comment by kgeographer** [comment]
done & closed
