### ISSUE TITLE
Search on Home Page is `exact`

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#259]
Ought to be `Similar to`, otherwise users are too often deterred by big red Nope.

**Comment by kgeographer** [comment]
Or they could be deterred by a firehose returned by similar; bears experimentation

**Comment by docuracy** [comment]
- [ ] Fix bug in Search, somewhere in the code which counts countries
- [ ] Switch Home Page mode to "Similar To" (already leads to Search page)
