### ISSUE TITLE
Info button does nothing (place collection builder)

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#261]
While editing a Place collection, the "making a collection public" button, to the right of "Public?: False" doesn't do anything.

![image](https://github.com/WorldHistoricalGazetteer/whg3/assets/173374768/6d80e058-309d-4cd6-b2d2-d4bab6b8842b)

**Comment by docuracy** [comment]
May get fixed in #303

**Comment by docuracy** [comment]
Fixed with #303
