### ISSUE TITLE
Mismatching node colors on Place Collection Map

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#262]
The colors appear to be incorrect on the Place Collection map. In this example, the orange is "no relation" and the island in the upper left should be the bright red of "non-Cretan site"... as a secondary issue, the "no relation" is actually "undefined", and I would prefer to see that in the legend rather than "no relation".

![image](https://github.com/WorldHistoricalGazetteer/whg3/assets/173374768/cc098162-f4d9-4a5f-818e-860de1dc534a)

**Comment by docuracy** [comment]
The markers are partially transparent and basemap colours therefore affect the rendered colours. I've cranked the opacity up from 70% to 85% and that seems to have made a significant improvement.

@kgeographer : what do you think of the suggestion that we change the _no relation_ legend to _undefined_ ? Unfortunately, that looks to me like an uncaught JavaScript error, so how about simply _other_ ? That's what I've switched it to in the upcoming PR (line 155 in `utilities.js` if you fancy something different).

![Image](https://github.com/WorldHistoricalGazetteer/whg3/assets/42514781/8625040e-f1f3-4b71-ab4e-dd0471ecb23c)
