### ISSUE TITLE
Markers on datasets getting multiple colors

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#264]
A dataset has no dimension on which marker color should change (unlike place collections), but they do:

<img width="740" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/3067bab0-fa4e-4fa6-96af-26fc74e297c2">

**Comment by docuracy** [comment]
Those in blue are features identified as water bodies.

**Comment by kgeographer** [comment]
Never differentiated them before, but if we must for some reason, a legend would be in order, no?

**Comment by docuracy** [comment]
Merged into #396
