### ISSUE TITLE
Study area display and editing broken

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#267]
New study areas (Area model) are created correctly, and display when initiating a reconciliation task, but are not editable, and don't always display in select dropdown after creation for a recon task.

**Comment by docuracy** [comment]
More context would be useful for diagnosis of new areas not always displaying after creation. I assume we're referring to `DatasetAddTaskView` and its corresponding template `ds_addtask.html`.

**Required Fixes:**

- [x] `context['dropdown_data'] = get_regions_countries()` is missing from `AreaUpdateView`
- [ ] After a user area has been selected on the `addtask` screen, an `edit area` link should appear alongside the `create user area` link (which should be renamed `create new`). The link should include a `?next=` link back to the `addtask` screen, which needs to be implemented in `AreaUpdateView` (same as for `AreaCreateView`).
- [ ] The `userareas` in `DatasetAddTaskView` are not filtered by owner_id, but should be.
- [ ] There's a bug whereby selecting { new } from the bottom of the dropdown list leads to a server error.

---

Testing with http://localhost:8001/datasets/69/addtask

http://localhost:8001/areas/create/?next=/datasets/69/addtask
http://localhost:8001/areas/484/update

Both views use areas/area_create.html

**Comment by kgeographer** [comment]
The issues, viewed live on prod 06 July:
- from My Data, click to edit an existing area, nothing appears on the map, e.g https://whgazetteer.org/areas/480/update
- from My Data, create Area, saves and returns to admin_dashboard - should be My Data
- from Add Task, area just created does not appear in dropdown (does appear in My Data list, but no geometry displays
- from Add Task select existing Area, older ones appear on map; newly created ones don't
- from Add Task, create area -> saves, returns to Add Task correctly, but new area not available on dropdown.
- it has been intentional that members of the whg_admins group see all user areas in the Add Task dropdown
In database, all new records have been created:
<img width="594" alt="image" src="https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/56c41e47-c291-4dc6-be40-b632897ed75f">
