### ISSUE TITLE
Review screen numbering of markers

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#272]
As reported by Frank Smits of KNAW: 

" Hi Karl, 
I believe I found another bug, this time in your reconciliation viewer. Namely, the count in the list starts at 1 but in the map it starts at 0 (see image below.)"

![image](https://github.com/WorldHistoricalGazetteer/whg3/assets/1753945/0bd8eaf6-adf7-4529-94eb-9c010b6df42f)

**Comment by docuracy** [comment]
Analysis: The front-end code was designed on the basis that the first feature in the FeatureCollection provided by the View would have `properties.ds`="dataset", but this will not be the case where no geometry yet exists for the place.
