### ISSUE TITLE
Handle combination of start and attestation year; eliminate '9999's

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#275]
The Viabundus dataset ready to publish has both start and attestation_year values, not handled well in publication page, or underlying code. Turning on 'display temporal' illustrates this

**Comment by docuracy** [comment]
- [ ] Hide missing end values from table.
- [ ] If attestation_year is present, include in Detail box as (e.g.) ‘source year: 1962’.
- [ ] Fix `timespans` in database:
    - [ ] start: -99999
    - [ ] end: 9999
