### ISSUE TITLE
Second search not working from using search on home screen

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#276]
On the homepage, I am able to enter a place into the search box and click the magnifying glass icon to run the search (for example Reek). I am then brought to the result for Reek. When I try to search another location from this same screen, I am unable to run the search (either by clicking on the magnifying glass or hitting return).

When I do the same thing but instead of searching directly in the home screen, I click Search in the top bar. I am able to then search Reek and from the results page search a second new place successfully.

**Comment by kgeographer** [comment]
fixed!
