### ISSUE TITLE
published dataset page

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#28]
- http://localhost:8001/datasets/10/places (_for example_)

**Comment by docuracy** [comment]
**TO DO**

SG
- [ ] table row background color goes grey after map click on another marker
- [ ] detail box does not always update, or updates to wrong record 
- [ ] time-slider updates detail continuously

KG
- [ ] download options not operable
- [ ] external links not operable
- [ ] image minimum height regardless of abstract length
- [ ] omit when if null: When: earliest: null; latest: null
- [ ] modal popup with full metadata
- [ ] full image modal/sizing
- [ ] add-place-to-collection functionality missing

**Comment by kgeographer** [comment]
completed, subject to review post beta launch
