### ISSUE TITLE
"Add to collection" should be visible/available only if logged in

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#286]
...on published dataset page, ds_places.html

or a modal should inform the anonymous user that adding to a collection requires being a logged in user

**Comment by docuracy** [comment]
I don't see any "Add to collection" link or button - is this something I need to add for logged-in users rather than hide from those who are not?

**Comment by kgeographer** [comment]
this column and tooltip lead an anonymous user to actions they can't perform...
<img width="238" alt="image" src="https://github.com/user-attachments/assets/6a5bc1c7-ff69-420b-88f6-dd3859f47dd9">

**Comment by docuracy** [comment]
As it turns out, window.loggedin is a string, not boolean, so line #168 of `tableFunctions.js` should be:

`const check_column = window.loggedin == 'true' ? {`

Do you want a PR for that, or will you hotfix or take care of it some other way?
