### ISSUE TITLE
Cretan Violence on Homepage

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#289]
I think the Cretan Violence place collection on the homepage is a dummy. I have added an image to the Place collection and annotated all the nodes, but these don't appear when you navigate to the collection from the Homepage. 

Here's the homepage collection: https://whgazetteer.org/datasets/39/places

Here's my Place Collection: https://whgazetteer.org/collections/133/browse_pl

**Comment by jesse-obert** [comment]
I just realized, looking at the URLs, that the one on the homepage is a dataset, not a place collection. I think maybe I just need to be made the author on the dataset.

**Comment by kgeographer** [comment]
> I just realized, looking at the URLs, that the one on the homepage is a dataset, not a place collection. I think maybe I just need to be made the author on the dataset.

You are creator on the dataset, but for the collection that was blank. I added your name to that and made the collection featured on the home page, in place of the dataset -- sound okay?

**Comment by jesse-obert** [comment]
Thanks! The collection does not appear on my dashboard. My username is jesobert. 

Ps after talking with Ali, I don't think I have admin powers either. Am I using the wrong account?

**Comment by kgeographer** [comment]
The collection "Violence on Crete, c.700-400 BCE" at https://whgazetteer.org/collections/133/browse_pl is owned by user 'jesobert' and as such should appear on your My Data page. 
Your account was not flagged as staff, changed that. Also added it to some groups it should have been in.
Now at least you can access it from admin dashboard; if still missing from My Data, please advise

**Comment by jesse-obert** [comment]
I now have access to the admin dashboard, thanks! 

The place collection was based on this dataset, https://whgazetteer.org/datasets/39/browse, which I don't have access to. I can't make myself a collaborator nor view the metadata. Can someone make me a collaborator, please? I just want to add an image, so there's no rush.

**Comment by kgeographer** [comment]
You are now owner of #39. We had the dataset in our test database prior to the migration and ids got screwed up. Sorry about that
