### ISSUE TITLE
Edit for LP-TSV spreadsheet template

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#295]
Hi - can someone please update the LP-TSV spreadsheet template to reflect that aat_types are required now. (they are required now, right? Louise is getting errors for missing ones). Thanks!

**Comment by alexstrb** [comment]
also, the link to the aat_types under the format guide tab on the spreadsheet template is broke: https://tinyurl.com/4n7epz8z

**Comment by kgeographer** [comment]
I am on it. I updated the one downloadable from the Create Dataset page, but not on github

**Comment by kgeographer** [comment]
> Hi - can someone please update the LP-TSV spreadsheet template to reflect that aat_types are required now. (they are required now, right? Louise is getting errors for missing ones). Thanks!

The requirement is not for aat_types, it is for **either** fclasses or aat_types

**Comment by alexstrb** [comment]
Ok, got it. The updated template is totally clear. Thanks!

**Comment by kgeographer** [comment]
All relevant templates and links are fixed
