### ISSUE TITLE
Dataset Upload validation bug

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#298]
Hello - Louise messaged me telling me she is getting an error when trying to upload a dataset that says "The dataset label entered is already in use, and must be unique. Try appending a version # or initials." She said she tried a bunch of different labels but nothing worked. I was able to get the same error on my end. See screen shot attached. 

![Screenshot 2024-07-16 163538](https://github.com/user-attachments/assets/ca1100db-2426-40de-9090-d73765a7ed77)

**Comment by alexstrb** [comment]
So update - after getting the error message I closed out whg and reopened it to find that the dataset did indeed upload successfully. Going to troubleshoot with Louise a bit and will write back with anything.

**Comment by alexstrb** [comment]
So looks like I am able to upload datasets fine, but Louise still cannot. She tried on Chrome and Safari but keeps getting the same error message. Please let me know if there's anything on her end that I can relay to her. Thanks!

**Comment by docuracy** [comment]
Interesting ... this chimes with some of the errors I've been getting while redeveloping the upload form and its validation. Within a few days (I hope) it'll look more like this and be more robust.

![image](https://github.com/user-attachments/assets/aac63abd-ec58-46dd-8e5a-424078aee335)

**Comment by alexstrb** [comment]
ok cool, thanks! Keep me posted and I'll have Louise give it a try again when it's ready.

**Comment by docuracy** [comment]
I've just rebooted the server with the simplified upload form. Do please give it a spin and let me know of ANY problems...

**Comment by alexstrb** [comment]
Louise was able to upload without this error. Thanks!
