### ISSUE TITLE
Place Detail `fclasses`

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#301]
Absent `types`, Place Detail does not return any `fclasses`-based "Type".

Base on `main.choices.FEATURE_CLASSES`

**Comment by kgeographer** [comment]
> Absent `types`, Place Detail does not return any `fclasses`-based "Type".
> 
> Base on `main.choices.FEATURE_CLASSES`

I would preface that with 'For LP format, ' because `types` in LP-TSV is simple text, never computed or mapped to anything.
