### ISSUE TITLE
Replace `.selector` modal dialogs

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#303]
Some pages are still using the old contact form, some because they are not using any base template. Are some of them redundant, @kgeographer ?

- [ ] media/help/going_public_coll.html
- [ ] media/help/going_public_ds.html
- [ ] media/help/whatsnew21.html

I suspect that these are new files which haven't reached my current branch yet:

- [ ] main/templates/tutorials/choosing.html
- [ ] main/templates/tutorials/place_collections.html

They too should be using `base_webpack` and `<a data-whg-modal="/contact_modal/">`.

**Comment by kgeographer** [comment]
the going_public html files are content that get loaded into modals on the builder/update pages for place collections and datasets (ds_metadata); therefore do not need any base. both links to load them are broken, despite the files being in place in media/help and listeners in place in `builders-collection-place.js` and `builders-dataset.js`. In the first case, there is a `$(".selector").dialog(` block, in the latter there is none.

all files under main/templates/tutorials are obsolete and should just be ignored for now. getting rid of them requires surgery: urls_guides.py and all references to `guides:<anything>` need to go away. recently tried and failed to excise completely and django barked loudly for days. leave this open - @kgeographer will attend to that one day. no urgency at all.

**Comment by docuracy** [comment]
Check the following for use of `.dialog()`. Convert `.selector` listeners and others to use `whg_modal` script:

- [ ] collection/templates/collection/collection_group_detail.html
- [ ] collection/templates/collection/collection_group_gallery.html
- [ ] datasets/templates/datasets/dataset_create_empty.html
- [ ] datasets/templates/datasets/ds_collab.html
- [ ] datasets/templates/datasets/ds_reconcile.html
- [ ] elastic/templates/elastic/index_admin.html
- [ ] elastic/templates/elastic/place_relocate.html
- [ ] resources/templates/resources/teaching.html

Check following pages for use of `.selector` dialogs:

- [ ] collection/templates/collection/collection_group_gallery.html
- [ ] collection/templates/collection/ds_collection_build.html
- [ ] collection/templates/collection/place_collection_build.html
- [ ] datasets/templates/datasets/accession.html
- [ ] datasets/templates/datasets/dataset_create_empty.html
- [ ] datasets/templates/datasets/ds_addtask.html
- [ ] datasets/templates/datasets/ds_gallery.html
- [ ] datasets/templates/datasets/ds_metadata.html
- [ ] datasets/templates/datasets/ds_status.html
- [ ] datasets/templates/datasets/review.html
- [ ] elastic/templates/elastic/index_admin.html
- [ ] elastic/templates/elastic/place_relocate.html
- [ ] main/templates/main/workbench_3col.html
- [ ] resources/templates/resources/teaching.html
