### ISSUE TITLE
Cannot Access Metadata in Admin Dashboard

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#304]
Hi

When I go to Admin Dashboard then click on a dataset that's not mine then edit then metadata, I get a page that says "Access to this page is limited to the dataset owner and designated collaborators." Can I get access to this? Jesse also does not have access. Thxxxxx!!!!!!

**Comment by docuracy** [comment]
It looks as though Karl has already fixed this, Ali. Would you please check that it's OK now? If so, please feel free to use the "Close with comment" button on the GitHub Issue (assuming you can see it).

**Comment by alexstrb** [comment]
Karl fixed - thanks!
