### ISSUE TITLE
Make geographical coordinates easily visible

### ISSUE THREAD

**Issue by rmostern** [WorldHistoricalGazetteer/whg3#324]
Suggestion from Manjusha Kuruppath: "I have a query about how to find the geographical coordinates for places on the latest version.  For instance, for a place like [Mysore] I am able to find the place in multiple datasets, its appellations and place type information but not the geographical coordinates. Can you please let me know where I can find them?"

--> could be a hover over at each point?  With maybe a way to right click or something to copy the coordinates if someone wants to paste them somewhere?

**Comment by docuracy** [comment]
See also #300

**Comment by docuracy** [comment]
Fixed and ready to push through to production server on next update.
