### ISSUE TITLE
dataset browse page (owner)

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#34]
- `/datasets/templates/datasets/ds_browse.html`
- Localhost example: http://localhost:8001/datasets/9/browse
- https://docs.google.com/presentation/d/1rzcLkYCEHoN1jUqX-M1O9VJfYq2Gnw--/edit#slide=id.p4

**Comment by kgeographer** [comment]
The map is not extraordinary, but the table is.

The django context variables delivered to the page include the booleans `wdtask`, `whgtask`, and `tgntask`. `tgntask` is deprecated). These are true if there is a task in the `django_celery_results_taskresult` table with status==SUCCESS (old tasks are kept and tagged ARCHIVED).

NB. At the moment there are no tasks in the table because a bug is preventing wikidata reconciliation from logging activity

When the table is drawn, columns are included for 'wikidata' and/or 'whg' id `wdtask` and/or`whgtask` are true

All Place records have `review_wd`, and `review_whg` values tracking their review status - NULL initially, but after a reconciliation task has been run, one of 
```
    (0, 'Unreviewed'),
    (1, 'Reviewed'),
    (2, 'Deferred')
```
Those status levels are reflected in the wikidata and whg columns, as an empty checkbox, a checked checkbox, and the string 'deferred' (or 'no hits' if NULL. For deferred, there is a link back to that record in the review screen.

Once a task is initiated (and a corresponding colmn is added to the table), a 'Review filiters' dropdown appears.

In this way, dataset owners and collaborators can track their progress through review.

Also note that upon accepting a match in the review screen, one or more place_geom and place_link records are written to the database, and these are reflected in the map (place_geom) and detail box (place_link) below it.

That's about it :^)

**Comment by docuracy** [comment]
Improve Map/Table interaction?
