### ISSUE TITLE
LP-TSV augmented download unavailable for either LP-TSV or LPF datasets

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#340]
In v2, once reconciliation had begin on a dataset, an option to download the augmented data was available, (now on ds_metadata tab). If a dataset came in as LP-TSV, 2 download links appeared - one 'as lp-tsv' the other 'as Linked Places json' (or similar), If the dataset came in as LPF, that option was displayes and a message that LP-TSV was not available for it (LPF complexity is not serializable as .tsv).

This logic seems to have been lost, e.g. [`https://whgazetteer.org/datasets/1521/metadata`](https://whgazetteer.org/datasets/1521/metadata)

It is also not possible to download an augmented version of an LPF dataset, e.g. \#838 (Bregel).

<img width="551" alt="image" src="https://github.com/user-attachments/assets/336b6353-ff78-4d31-bacc-60325ab8683b">

**Comment by docuracy** [comment]
Various problems:

Crete Violence dataset: /datasets/39/places
- File user_2/crete_violence.tsv does not actually exist in the server's media folder
-

**Comment by docuracy** [comment]
Remaining problem is simply that clicking the LPF download button provides no status feedback (task query returns 404 because it is already complete and purged?): in fact the augmented LPF is generated and available from the My Data page.

**Comment by docuracy** [comment]
Not entirely resolved, but: 

- uploaded file is available on owner's dataset metadata page
- LPF version also available if upload was delimited
- link to generate augmented LPF
- no longer possible to generate augmented TSV

- LPF is the only download option on public pages

It's unclear how TSV might have been offered for augmented data in the past: LPF could be flattened to delimited text (fLPF), and optionally then reduced to LP-TSV, but in that case which properties should be retained?

**Comment by kgeographer** [comment]
> It's unclear how TSV might have been offered for augmented data in the past: LPF could be flattened to delimited text (fLPF), and optionally then reduced to LP-TSV, but in that case which properties should be retained?

Not certain, but as I recall, the augmented LP-TSV simply added a "matches" column, with a ';' delimited list of matched (and aliased) identifiers. Nothing was done to accommodate the new v3 option of accepting place names as an augmentation.

Not satisfactory, obv. -- the idea was that for people just doing some geocoding, they would get the geometry they were after, and it was on them to incorporate that new data into their working 'master.' Using the same principle, one could add a 'variants' column if there hadn't been one, or append to one if there had.

$.02
