### ISSUE TITLE
Download dataset operation failing

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#341]
A dataset can be downloaded from either ds_metadata (by its owner), or from a modal in its ds_place "pub" page (preview until made public). 
- from ds_metadata, a spinner appears and hangs, a link is correctly created and appears on the owners My Data page
- from ds_places, a message "Download complete!" appears, and a link is created and appears on the owners My Data page
- In both cases 
  - the link on the MyData page returns a 404 error, 
  - no email is sent

**Comment by docuracy** [comment]
Thanks for the alert:

- `ds_metadata` spinner and email-sending are slated to be dealt with separately
- Everything in the media/downloads folder is a .zip file, but the links seem to be to unzipped equivalents. Will investigate...

**Comment by docuracy** [comment]
... utils.tasks is generating zipfiles after doing `create_downloadfile_record` with the unzipped filename.
