### ISSUE TITLE
Move or replace WHG blog 

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#345]
The WordPress blog, (blog.whgazetteer.org) lives on @kgeographer's personal VM, and need to move.

It requires a 'LAMP stack' - i.e. linux, apache (nginx is fine), mysql, and php. MySQL and PHP are not currently installed on the server. 

- the site folder currently uses 1gb; the server has ample space 
- the site get very little traffic; 
- based on current usage and settings, MySQL would use about 75mb ram

Some alternative options:
- establish a new blog site, e.g. on github but this will require a fair amount of configuration
- create a new small Digital Ocean droplet using a snapshot of @kgeographer's, after it has been "cleaned out" of non-WHG material

**Comment by kgeographer** [comment]
I can attempt the move, once given the go-ahead. I would like this to happen fairly soon, as I need to replace my droplet with something bigger for my personal experimentation. If this takes a while, I could submit my monthly DO rent (~$13) as an expense at some point.

**Comment by docuracy** [comment]
OK - but probably easiest to add to the existing WHG Docker network using the official Wordpress and mysql images. I should be able to get round to it before the end of August - would that be soon enough?

**Comment by kgeographer** [comment]
Docker for the WordPress+LAMP stack makes sense; imagine the import of existing content may be tricky but doable.

**Comment by docuracy** [comment]
I might actually get this done in the next day or two while fiddling with compose file templates: could I trouble you to put a wordpress database (as a `.sql` file) and content/configuration dump (including probably a `wp-content` folder and maybe a `wp-config.php` file) in the new `~/wordpress` folder on the server, please, @kgeographer? I'll adjust the DNS and Nginx configuration.

**Comment by docuracy** [comment]
https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-with-docker-compose
