### ISSUE TITLE
newly published dataset 1535 issues

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#351]
- error screen when trying to make the dataset public. @alexstrb tried to make it public from both the metadata screen and [whgazetteer.org/admin](http://whgazetteer.org/admin). 
  - @kgeographer switched `public=true` in database, but flag fails from interface

- (@kgeographer) added a photo, which is uploaded correctly but does not display.

**Comment by docuracy** [comment]
Metadata form validation was janky wrt `webpage` and `uri_base` - sorted out in a separate Issue.

Photo seems to be displaying correctly.
