### ISSUE TITLE
Uploaded dataset images fail to display

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#357]
All the steps behave normally on the Metadata tab: choosing an image, uploading, saving the form.
The image file appear in correct location on disk, and in page markup - e.g. `src="/media/datasets/1535_solar-eclipse.jpg"
But image does not display, with 404 error in browser's Network console...
Datasets with existing images are ok, but new ones aren't found

<img width="773" alt="image" src="https://github.com/user-attachments/assets/16873786-beb0-4dea-97bb-a0846747212b">

**Comment by docuracy** [comment]
Seems to have been fixed by rebooting Nginx - perhaps a problem related to #358 (fixed)
