### ISSUE TITLE
Collections Bug

### ISSUE THREAD

**Issue by alexstrb** [WorldHistoricalGazetteer/whg3#367]
This issue happened to me first on my "Charli XCX" collection and I was able to replicate it on my "Where in the World is Carmen San Diego Collection." Under visualization options, I had sequence, trail, and sort all clicked. When I hit save, I got stuck on a loading screen telling me the collection was loading. I am still not able to access either collection and just get the loading screen. When I do not have trail clicked, I don't seem to get the same problem. 

![Screenshot 2024-09-16 122023](https://github.com/user-attachments/assets/66bbd38e-3c6b-402e-99fb-46bb493a8e33)

**Comment by alexstrb** [comment]
I could click edit from the my data screen and once I unclicked "trail" the collection was fine again.

**Comment by docuracy** [comment]
Sorry, and thanks for raising this - there's an update currently in staging on the dev server which should resolve it. I need to fix a few other things before pushing it out to the production server in the next day or two.

Incidentally, if you open browser developer tools (F12 in Chrome/Windows) there are often error messages like this in the console which will indicate what's gone wrong and whether it's worth waiting for something else to happen.

![image](https://github.com/user-attachments/assets/d97169f3-9f35-43fa-ac0a-cdc934fda78c)

**Comment by docuracy** [comment]
Fixed and ready to push through to production server on next update.
