### ISSUE TITLE
Kato Syme Geometry

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#368]
Hello,

I noticed that Kato Syme is in the wrong spot.

WHG: https://whgazetteer.org/places/7551937/detail 
Pleiades: https://pleiades.stoa.org/places/589805 

This is 100% my bad, but I don't know how to proceed. Should I delete my dataset and start over (losing my place collection as well) or can you fix it's geometry internally? 

Thanks in advance.

Best,
Jesse

**Comment by docuracy** [comment]
Hi, no, DON'T delete it! There has to be a better way ... leave it with me ...

**Comment by docuracy** [comment]
Done. But this kind of thing really underlines why we need better built-in GIS features.
