### ISSUE TITLE
Relations Issue

### ISSUE THREAD

**Issue by justinpiel** [WorldHistoricalGazetteer/whg3#373]
On the "Bulgar Origins and Travels" dataset, I have defined 5 relations and given them out to all 70 places, but in the "view" tab, all still show up as "other." Thank you!

-Justin P

**Comment by docuracy** [comment]
Oddly, seems to be fine on my local system - will investigate...

![image](https://github.com/user-attachments/assets/c7dad7a0-64f6-4417-b908-e15008882e5d)

**Comment by docuracy** [comment]
Fixed.

Required update of cached mapdata. This is now updated automatically whenever `rel_keywords` are changed.
