### ISSUE TITLE
Spelling Error ZimonyiVolga

### ISSUE THREAD

**Issue by justinpiel** [WorldHistoricalGazetteer/whg3#374]
On my dataset "ZimonyiVolga," I realized that I misspelled record 7554870 as "Atelkozuzou" instead of the correct "Atelkouzou." My apologies for the mistake!

-Justin Piel

**Comment by docuracy** [comment]
No worries - I'll fix that when I get a chance - thanks for letting me know!

**Comment by docuracy** [comment]
Fixed ... I think ...
