### ISSUE TITLE
Manual reconciliation

### ISSUE THREAD

**Issue by robcast** [WorldHistoricalGazetteer/whg3#375]
I mostly used WHG as a geocoding tool for our ISMI database (https://whgazetteer.org/datasets/1304/places) and other projects referring to historical places.

In the current version the verbatim place name match in the first reconciliation step worked fine but it only matched 127 of the 389 records and there is no further fuzzy or manual matching steps.

The reconciliation UI is really good (much better than OpenRefine) and it would be a really valuable tool if it were possible to get additional automatically generated fuzzy match candidates to currently unmatched place names and the opportunity to just use the existing place search to identify a place manually and assign it as a match in the reconciliation.

**Comment by docuracy** [comment]
Thanks for the suggestions!

As we discussed by email, the current recommendation is for uploaded datasets to include at least one modern country code corresponding to each place, and doing so seems to have resolved your problem.

I anticipate that the proposed Place Matching Engine (https://github.com/WorldHistoricalGazetteer/whg3/issues/381) will radically improve the reconciliation in due course.
