### ISSUE TITLE
Deadlink - time sensitive

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#378]
Hello,

I found a deadlink. From the homepage > Teaching > "Create and manage a collection group" > https://whgazetteer.org/teaching/documentation/#collgroups "Sorry, the requested page does not exist" 

We need this by Saturday Oct. 5th, for our teaching workshop.

Thanks, 
Jesse

**Comment by docuracy** [comment]
Fixed in my local branch - will push it out to the server later if I manage to squish #379 too.
