### ISSUE TITLE
Tyre cannot be added to a place collection

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#379]
Hello,

When I try to add Tyre (https://whgazetteer.org/places/13452093/portal/) to my teaching place collection, it doesn't work. 

Best,
Jesse

**Comment by docuracy** [comment]
Fixed a problem in the database with place_id =8165142, where minmax values and timespan (actually yearspan) values were stored as strings and not integers. That shouldn't arise again for newly-accessioned data with the new validation workflow, but there may be others in the dataset which require cleaning.

Please check and let me know if fixing this has solved the problem of adding the place to your collection.
