### ISSUE TITLE
Annotation editing: improve UI with AJAX

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#380]
Hello,

Thanks for squashing 378 and 379, they appear to be working!

I have new issues (that may ultimately just be a future problems). When I'm annotating places on the place collection page:

- I can't save my annotations unless I input dates. This shouldn't be required because some folks may not have dates for the places in their collections.
- When I save, the page resets and takes me back to the main page.
- Once I have annotated a place, I can't see those annotations on the Add Annotation page... it just says "annotated." To see the annotations I have to click on "view" my collection  

Thanks in advance! It would be great to have all these by Saturday, which I know is a big ask.

Best,
Jesse

**Comment by docuracy** [comment]
- [x] Enable saving of annotations without dates
- [ ] Implement AJAX for submission of form to avoid navigation away from tab and annotation
- [ ] Alert on validation errors
