### ISSUE TITLE
DK Atlas duplicates

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#387]
Hello,

For a lot of place portal pages, there are two identical entries for the DK Altas. Here's an example: https://whgazetteer.org/places/12345963/portal/

Can we merge these or something to clean up the place portal page? A lot of teachers at the workshop on 10/5/2024 expressed confusion about the duplication.

Best,
Jesse

**Comment by docuracy** [comment]
The trouble with that particular example - and perhaps the others that you observed - is that these are separately attested within the DK Atlas as different places with different coordinates at different times, although they share the same name. Somebody must have linked them at some point. I'm inclined to leave well alone until we've perhaps got some auto-matching system in place and can root out bad links, if indeed that's what these are.
