### ISSUE TITLE
Duplicates in Cretan Violence Dataset

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#390]
Hello,

There are two of every place in the Cretan Violence dataset: https://whgazetteer.org/datasets/39/places

Can we delete the duplicates?

Best,
Jesse

**Comment by docuracy** [comment]
As far as I could see in the database, you had a set of 61 places `created` 28 Aug 2023, and another set of 61 `created` 17 Dec 2023.The latter set is not reviewed or indexed, and I suspect it was the result of some data manipulation during the switch to v3 which might have affected other datasets too. Erk.

Fortunately, only the first set had been added to any Place Collection (no.133), so I've gone ahead and wiped the other set (using the Django Admin interface).
