### ISSUE TITLE
Accessioning Review

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#394]
Problem saving dataset when "no match" or more than 1 "close match" places are selected.

Noted with these datasets, neither of which had geometry originally:

- Avars
- New Rome

**Comment by jesse-obert** [comment]
This happened again. I think it's just every time I try to save a No Match.

**Comment by jesse-obert** [comment]
Happened with New Rome too. Louise's original didn't have any geometry, so I didn't match it. It seems to consistently go wrong when I save a "no match"

**Comment by docuracy** [comment]
If `indexMatch` received a `pid` value of `None`, it would crash.
