### ISSUE TITLE
Dataset Collection enhancements

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#396]
- [x] Gallery page cards for collections should discriminate between dataset and place collections

- [x] Collections have a database `creator` field but no means of adding a value: update the `metadata` forms for both place and dataset collections
- [x] Components of a Dataset Collection need to be indicated on a browse_ds page (e.g. https://whgazetteer.org/collections/172/browse_ds) by colouring the map markers and using the same key module as is used by Place Collections to indicate `relations`. [~Also remove colour differentiation for water features in Datasets~]
- [x] LPF downloads of both datasets and collections should include full CSL/`schema.org` citations (see also #314)
- [x] Publication of both datasets and collections should offer minting of a DOI (#406)

**Comment by jesse-obert** [comment]
I noticed that this one has color: https://whgazetteer.org/collections/127/browse_ds. Maybe it's already distinguishing between different datasets? I don't know and it's unclear. I'll edit this if I think of any other things to improve, but this sounds like an excellent list so far! Thanks Stephen!

**Comment by docuracy** [comment]
Ah- that was the gist of https://github.com/WorldHistoricalGazetteer/whg3/issues/317

**Comment by alexstrb** [comment]
Hi Stephen -  I was wondering if it would be possible to add the ability to click datasets on and off in a dataset collection? So for example for the Historical Gazetteer of Central Asia (https://whgazetteer.org/collections/127/browse_ds) there would be a way to click "off" for some datasets like if I wanted to see which ones incorporated places in India and which ones did not. I know the purpose is to see all the places together but sometimes it's just looks like so many dots. I don't know what do you think?
