### ISSUE TITLE
Cannot search the WHG on my Android 

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#398]
I tried searching for a place on my phone, and it does not work. Ali can do it, but nothing works for me. I have an Android, Ali has an iPhone.

![Screenshot_20241018_153108_Chrome](https://github.com/user-attachments/assets/33352d9c-9030-4be1-a18e-5e5cba7b54e9)

**Comment by docuracy** [comment]
Fixed in next update
