### ISSUE TITLE
CC License 

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#400]
Our CC license was listed in the documentation of the v2 page, but Ali and I couldn't find it on the v3 page. Can we list it somewhere (if it isn't posted already)?

Based on our notes from last year, before the transition to v3, place attestations were covered under the CCBY 4.0 non-commercial license.

Thanks!

**Comment by docuracy** [comment]
Related to #200

**Comment by docuracy** [comment]
The `licensing` page is linked as "WHG Policy" in the download instructions, wherever they appear:

![image](https://github.com/user-attachments/assets/7ddf6136-6b9e-4aaf-9ace-fe6e53344266)

I'm going to split it into modal overlays linked from the page footer as Licence | Terms of Use | Privacy Policy

**Comment by docuracy** [comment]
Job done - will push to production server overnight (US time).
