### ISSUE TITLE
Accessioning Brick Wall

### ISSUE THREAD

**Issue by jesse-obert** [WorldHistoricalGazetteer/whg3#423]
Hi Stephen,

Okay, I found the first issue. If you try to mark two places as a close match...

![image](https://github.com/user-attachments/assets/3c3fac04-6e27-4d81-bf51-a06841c59359)

... like in the screenshot: this Mecca is both of the Meccas listed. If you say it's both Meccas, then you run into this screen:

![image](https://github.com/user-attachments/assets/7e1cee84-c296-4fe2-8fba-e9bca6dce543)

The second error occurs when you say that some place is not a close match. I will update this issue post, once I have screenshots.

Edit: okay, now I run into the "something went wrong" page even when I try to mark a spot as a close match. I'll try to restart and look for more bugs in a couple hours.

**Comment by docuracy** [comment]
Thanks for the report!

Note to self: when I get round to investigating, I'll need to look into these (related?) errors:

```text
Traceback (most recent call last):
  File "/py/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/py/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/datasets/views.py", line 999, in review
    indexMultiMatch(place_post.id, matched_for_idx)
TypeError: indexMultiMatch() missing 2 required positional arguments: 'user' and 'task'
```

```text
Traceback (most recent call last):
  File "/py/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/py/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/datasets/views.py", line 994, in review
    indexMatch(str(place_post.id), hit_pid=parent_id, user=request.user, task=task)
  File "/app/datasets/views.py", line 378, in indexMatch
    hit = res['hits']['hits'][0]
IndexError: list index out of range
```

**Comment by docuracy** [comment]
Well... 

I found quite a few missing variables in the context for `review.html`, and some that were being rendered as Python boolean string-equivalents instead of JavaScript boolean values. Fixed those, and I no longer see errors in the sandbox copy of the site. Please re-open this Issue with further screenshots if/when you find more problems...

**Comment by docuracy** [comment]
... but hang on, I've spotted some other things...

**Comment by docuracy** [comment]
... OK, please try that.

I rewrote `indexMatch` which had some funky logic, and fixed some missing parameters in a call to `indexMultiMatch`.

**Comment by kgeographer** [comment]
Funky logic was a specialty 😎. Also, sorry about that.
