### ISSUE TITLE
Place Detail page

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#50]
- [Slide](https://docs.google.com/presentation/d/1rzcLkYCEHoN1jUqX-M1O9VJfYq2Gnw--/edit#slide=id.p3)
- Template: /places/templates/places/place_detail.html
- View: PlaceDetailView(DetailView)
- URL Pattern: '<int:id>/detail'
- Example on localhost: http://localhost:8001/places/730/detail
- Example on v2: https://whgazetteer.org/places/2487384/detail

**Comment by kgeographer** [comment]
- copy coordinates link broken

**Comment by docuracy** [comment]
I think it _is_ working, but the popup text was not being updated. I've added the second line below to fix that.

```
				.attr('data-original-title', 'copied!')
				.attr('data-bs-original-title', 'copied!')
```
