### ISSUE TITLE
Add Reconciliation Task

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#51]
- [Slide](https://docs.google.com/presentation/d/1rzcLkYCEHoN1jUqX-M1O9VJfYq2Gnw--/edit#slide=id.p6)
- Template: /datasets/templates/datasets/ds_addtask.html
- View: DatasetAddTaskView(LoginRequiredMixin, DetailView)
- URL Pattern: '<int:id>/addtask'
- Example on localhost: http://localhost:8001/datasets/8/addtask
- Example on v2: https://whgazetteer.org/datasets/956/addtask

**Comment by kgeographer** [comment]
- Agree there is no need for popups on this map, for either type of region
- `area_create_og.html` in update mode does not display geometry for either type of region. the Dashboard allowing listing of pre-defined is an error; those should not be editable by anyone. 
- No drawing tools for editing areas are available

**Comment by docuracy** [comment]
The `area_create_og.html` page isn't yet on my task list - is that where you're lacking the drawing tools for editing areas ?

**Comment by kgeographer** [comment]
I saw reference to `area_create_og.html` somewhere and assumed that was the active page -- but now see it is `area_create.html` - so never mind. The 'og stands for 'original' and sometimes I make a backup before doing something radical and gall -t _bak or _og. I'll get rid of it eventually.

**Comment by docuracy** [comment]
**TODO:**

- [ ] Something janky happens when switching the Pass selector - `mapParameters` and presumably other variables are not loaded from HTML template.
