### ISSUE TITLE
Place Portal page

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#53]
- `\places\templates\places\place_portal.html`
- v3 localhost: http://localhost:8001/places/portal/ **<- but has to be reached from http://localhost:8001/search/**
- v2 example: https://whgazetteer.org/places/12346428/portal
- class PlacePortalViewNew(TemplateView)

Just a layout so far. Code to arrive from search results page with necessary context is prepped, needs to be folded into other work on the search results page.

**Comment by docuracy** [comment]
TODO:

- [ ] Interlink Sources table and map features
- [ ] Implement temporal filtering
