### ISSUE TITLE
Dateline: `Help`

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#85]
- [ ] help modal action (sg - add hover (red #993333) or click (blue) [?] fa-question-circle button)
- [ ] help modal content (kg, sg)

**Comment by docuracy** [comment]
What needs to be said?

**Comment by kgeographer** [comment]
Maybe if there is a time slider it should be open by default, where it is obvious what it is and needs no help. Easy to miss when closed.

**Comment by docuracy** [comment]
OK, easy enough to set the control to be open by default, and the initialisation automatically encompasses the entire range of dates present in the dataset/collection and has `Include undated` checked by default.

Perhaps there's a case for a detailed explanation in a popover, which would have a `Don't bug me with this again any time soon` button to set a disabling cookie?
