### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#91]
- [x] - per-item vis_parameters for map
- [x]     - adjust code from current defaults (sg)
- [x] - announcements
- [x]     - django model (kg)
- [x]     - rolling/scrolling in `<div>` (sg)
- [x] - text content (kg, team)
- [x] - alternate layout/architecture (kg)
- [x]     - big buttons to pages not modals? (kg)
- [x] - site nav menu options (kg)

---

- [x] Modify `featureCollectionAPIView` to test for existence of tileset, and (potentially) return empty featureCollection
- [x] Modify `fetchDataForHorse` function in `localGeometryStorage.js` to (optionally) use extent from tileJSON

**Comment by kgeographer** [comment]
Done, notwithstanding last second css tweaks to follow
