### ISSUE TITLE
Search Page: Misc.

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#92]
- [x] options for fuzzy, starts-with, contains, exact  ES (kg)
- [ ] result content display (kg)
  - [ ]      - modify ES search to get some child info
  - [x]      - differentiate, index vs db results visually
  - [x]      - do away with detail box?
  - [ ]      ~- explain index vs db results~
- [x] - css fussing (kg)
- [x] - team feedback in March

**Comment by kgeographer** [comment]
Closing; remaining task moved to #193
